### ISSUE TITLE
idea: set stream:false option to enable logging of API response

### ISSUE THREAD

**Issue by hello-tkh** [ks6088ts-labs/azure-openai-playground#18]
## What would you like to be added?
Option to set stream:false for Open AI API call.
Currently there is no good way to log API response when stream:true.
API response contains good information such as full text of completion, and token usage.

example:
    "usage": {
      "completion_tokens": 365,
      "prompt_tokens": 378,
      "total_tokens": 743
    }

## Why is this needed?
Being able to log full prompt and response text, as well as token usage is requested in some enterprise setting.

Sample implementation:
https://github.com/ks6088ts-labs/azure-openai-playground/compare/main...tkh85:azure-openai-playground:main

![スクリーンショット 2023-06-09 220555](https://github.com/ks6088ts-labs/azure-openai-playground/assets/114053294/83c07245-07a0-469b-b081-21b89f09de84)

![スクリーンショット 2023-06-09 221015](https://github.com/ks6088ts-labs/azure-openai-playground/assets/114053294/3e3f1fd7-0327-458f-88b5-aee2db213424)

**Comment by ks6088ts** [comment]
First of all, thank you for the suggestion, including sample implementation !
I understood that there are some requests to disable stream option.
I'll think about integrating the feature sometime soon.

**Comment by ks6088ts** [comment]
I created a pull request for implementing this feature referring to @tkh85 's sample implementation. Many thanks :)

**Comment by ks6088ts** [comment]
@tkh85 
Does PR #20  meet your needs?
